name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9714a7fde76207e62d129ec69ef900a6df7e5734359999924ba0b474db9bbef"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
