name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "974fef3fc9bad4456235be893e4b19037aef4bafa0197a45b7580fcd4800a443"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
