name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c133aa113e5c00ad303d1fc8dcc6e5cf329851a017235dd44924f7c6ea717ded"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
