name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8ce7859c8124c6e8b3ab1d82f32706a54a5ce62577c759e51b73abb411f33d3"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
