name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65a1b3aaf7a3d155d4d9bf22041fbe2a0ee93b86c40b7df43e6a63314dbb09ee"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
