name = "Aetheria"
author = "xhyrom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7145d0cfb82c554d7801e1c81045d9d0de489b1e9d7b30aa60655eef82d0b85"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
